# Generated by Django 4.2.6 on 2023-11-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="show_theme",
            field=models.ManyToManyField(
                null=True, related_name="astronomy_show", to="planetarium.showtheme"
            ),
        ),
    ]
