# Generated by Django 4.0.4 on 2023-11-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0004_astronomyshow_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronomyshow',
            name='show_theme',
            field=models.ManyToManyField(related_name='astronomy_show', to='planetarium.showtheme'),
        ),
    ]
