# Generated by Django 4.0.4 on 2023-11-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0005_alter_astronomyshow_show_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronomyshow',
            name='show_theme',
            field=models.ManyToManyField(blank=True, related_name='astronomy_show', to='planetarium.showtheme'),
        ),
    ]
