# Generated by Django 4.0.4 on 2023-11-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0006_alter_astronomyshow_show_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showsession',
            name='show_time',
            field=models.DateTimeField(),
        ),
    ]
