# Generated by Django 4.0.4 on 2023-11-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0007_alter_showsession_show_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planetariumdome',
            name='rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planetariumdome',
            name='seats_in_row',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
